
before_script:

stages:
  - test

unit_test_job:
  stage: test
  script:
    - python3 -m unittest discover
  only:
    - master

functional_test_job:
  stage: test
  script:
    - ./test.sh
  only:
    - master
